BEGIN;
INSERT OR IGNORE INTO bible_books VALUES(1,'Genesis');
INSERT OR IGNORE INTO bible_books VALUES(2,'Exodus');
INSERT OR IGNORE INTO bible_books VALUES(3,'Leviticus');
INSERT OR IGNORE INTO bible_books VALUES(4,'Numbers');
INSERT OR IGNORE INTO bible_books VALUES(5,'Deuteronomy');
INSERT OR IGNORE INTO bible_books VALUES(6,'Joshua');
INSERT OR IGNORE INTO bible_books VALUES(7,'Judges');
INSERT OR IGNORE INTO bible_books VALUES(8,'Ruth');
INSERT OR IGNORE INTO bible_books VALUES(9,'1 Samuel');
INSERT OR IGNORE INTO bible_books VALUES(10,'2 Samuel');
INSERT OR IGNORE INTO bible_books VALUES(11,'1 Kings');
INSERT OR IGNORE INTO bible_books VALUES(12,'2 Kings');
INSERT OR IGNORE INTO bible_books VALUES(13,'1 Chronicles');
INSERT OR IGNORE INTO bible_books VALUES(14,'2 Chronicles');
INSERT OR IGNORE INTO bible_books VALUES(15,'Ezra');
INSERT OR IGNORE INTO bible_books VALUES(16,'Nehemiah');
INSERT OR IGNORE INTO bible_books VALUES(17,'Esther');
INSERT OR IGNORE INTO bible_books VALUES(18,'Job');
INSERT OR IGNORE INTO bible_books VALUES(19,'Psalms');
INSERT OR IGNORE INTO bible_books VALUES(20,'Proverbs');
INSERT OR IGNORE INTO bible_books VALUES(21,'Ecclesiastes');
INSERT OR IGNORE INTO bible_books VALUES(22,'Song of Solomon');
INSERT OR IGNORE INTO bible_books VALUES(23,'Isaiah');
INSERT OR IGNORE INTO bible_books VALUES(24,'Jeremiah');
INSERT OR IGNORE INTO bible_books VALUES(25,'Lamentations');
INSERT OR IGNORE INTO bible_books VALUES(26,'Ezekiel');
INSERT OR IGNORE INTO bible_books VALUES(27,'Daniel');
INSERT OR IGNORE INTO bible_books VALUES(28,'Hosea');
INSERT OR IGNORE INTO bible_books VALUES(29,'Joel');
INSERT OR IGNORE INTO bible_books VALUES(30,'Amos');
INSERT OR IGNORE INTO bible_books VALUES(31,'Obadiah');
INSERT OR IGNORE INTO bible_books VALUES(32,'Jonah');
INSERT OR IGNORE INTO bible_books VALUES(33,'Micah');
INSERT OR IGNORE INTO bible_books VALUES(34,'Nahum');
INSERT OR IGNORE INTO bible_books VALUES(35,'Habakkuk');
INSERT OR IGNORE INTO bible_books VALUES(36,'Zephaniah');
INSERT OR IGNORE INTO bible_books VALUES(37,'Haggai');
INSERT OR IGNORE INTO bible_books VALUES(38,'Zechariah');
INSERT OR IGNORE INTO bible_books VALUES(39,'Malachi');
INSERT OR IGNORE INTO bible_books VALUES(40,'Matthew');
INSERT OR IGNORE INTO bible_books VALUES(41,'Mark');
INSERT OR IGNORE INTO bible_books VALUES(42,'Luke');
INSERT OR IGNORE INTO bible_books VALUES(43,'John');
INSERT OR IGNORE INTO bible_books VALUES(44,'Acts');
INSERT OR IGNORE INTO bible_books VALUES(45,'Romans');
INSERT OR IGNORE INTO bible_books VALUES(46,'1 Corinthians');
INSERT OR IGNORE INTO bible_books VALUES(47,'2 Corinthians');
INSERT OR IGNORE INTO bible_books VALUES(48,'Galatians');
INSERT OR IGNORE INTO bible_books VALUES(49,'Ephesians');
INSERT OR IGNORE INTO bible_books VALUES(50,'Philippians');
INSERT OR IGNORE INTO bible_books VALUES(51,'Colossians');
INSERT OR IGNORE INTO bible_books VALUES(52,'1 Thessalonians');
INSERT OR IGNORE INTO bible_books VALUES(53,'2 Thessalonians');
INSERT OR IGNORE INTO bible_books VALUES(54,'1 Timothy');
INSERT OR IGNORE INTO bible_books VALUES(55,'2 Timothy');
INSERT OR IGNORE INTO bible_books VALUES(56,'Titus');
INSERT OR IGNORE INTO bible_books VALUES(57,'Philemon');
INSERT OR IGNORE INTO bible_books VALUES(58,'Hebrews');
INSERT OR IGNORE INTO bible_books VALUES(59,'James');
INSERT OR IGNORE INTO bible_books VALUES(60,'1 Peter');
INSERT OR IGNORE INTO bible_books VALUES(61,'2 Peter');
INSERT OR IGNORE INTO bible_books VALUES(62,'1 John');
INSERT OR IGNORE INTO bible_books VALUES(63,'2 John');
INSERT OR IGNORE INTO bible_books VALUES(64,'3 John');
INSERT OR IGNORE INTO bible_books VALUES(65,'Jude');
INSERT OR IGNORE INTO bible_books VALUES(66,'Revelation');
COMMIT;
