# This action enables building release executables/installers and can be triggered manually or by release creation.
#
# Executables are built both for releases and for manually triggered runs, uploaded to artifacts and assets.
name: Release Mac Build

on:
  workflow_dispatch:
  # push:
  # tags:
  #   - "*"
  # branches:
  #   - build/test
  # pull_request:
  # merge_group:

# Incremental compilation here isn't helpful
env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    strategy:
      matrix:
        build:
          - os: macos-14
            target: aarch64-apple-darwin
            suffix: macos-aarch64-${{ github.ref_name }}
      fail-fast: false
    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install GTK4 (macOS)
        run: |
          brew install gtk4 librsvg

      # On macOS, we need a proper Clang version, not Apple's custom version without wasm32 support
      - name: Install LLVM and Clang for macOS
        uses: KyleMayes/install-llvm-action@dec985c8d7b46a2f363ea1a78f660c946a3349ea # v2.0.1
        with:
          env: true
          version: 17

      # Because macOS, see https://andreasfertig.blog/2021/02/clang-and-gcc-on-macos-catalina-finding-the-include-paths/
      - name: Configure C compiler macOS
        run: |
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

      - name: Install glibtoolize (macOS)
        run: brew install libtool

      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install automake (macOS)
        run: brew install automake

      - name: Configure cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build app (macOS, normal)
        env:
          RUSTFLAGS: ${{ matrix.build.rustflags }}
        run: cargo build --locked --target ${{ matrix.build.target }} --profile production

      - name: Create bundle (macOS)
        run: ./scripts/deploy_macos.sh

      # - name: Create dmg (macOS)
      #   run: |
      #     version=$(cargo pkgid | cut -d "@" -f2)
      #     npx appdmg@0.6.6 res/macos/spec-${{ matrix.build.target }}.json target/bundle/openworship-$version.dmg

      - name: Sign and notarize dmg (macOS)
        run: |
          echo "Signing"
          version=$(cargo pkgid | cut -d "@" -f2)
          codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime -s - build/openworship-$version.dmg

      - name: Upload dmg to artifacts (macOS)
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.1.3
        with:
          # name: openworship-${{ matrix.build.suffix }}
          name: openworship-macos-aarch64
          path: build/*.dmg
          if-no-files-found: error

      # - name: Upload dmg to assets (macOS)
      #   uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     asset_paths: '["target/bundle/*.dmg"]'
      #   if: runner.os == 'macOS' && github.event_name == 'push' && github.ref_type == 'tag'
