# This action enables building release executables/installers and can be triggered manually or by release creation.
#
# Executables are built both for releases and for manually triggered runs, uploaded to artifacts and assets.
name: Release Window Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  # push:
  #   #   # tags:
  #   #   #   - "*"
  #   #   branches:
  #   #     - build/test
  #   pull_request:
  #   merge_group:

# Incremental compilation here isn't helpful
env:
  CARGO_INCREMENTAL: 0
  APP_BUILDDIR: builddir

jobs:
  release-win:
    runs-on: windows-2022
    permissions:
      contents: write # needed for uploading release artifact
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure GTK4 cache
        uses: actions/cache@v5
        id: cache-gvsbuild-gtk
        with:
          path: |
            C:\gtk-build\gtk\x64\release
            C:\gtk-build\build
            C:\gtk-build\downloads
            C:\gtk-build\cache
          key: ${{ runner.os }}-gtk4

      - name: Configure cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable

      # - name: Install Inno 6
      #   id: install_inno
      #   shell: pwsh
      #   run: |
      #     if (Test-Path "C:\Program Files (x86)\Inno Setup 6\") {
      #       echo "inno already installed"
      #     } else {
      #       winget install -e --id JRSoftware.InnoSetup -v 6.4.3 --accept-package-agreements `
      #         --accept-source-agreements --disable-interactivity --scope machine
      #       if (Test-Path "C:\Program Files (x86)\Inno Setup 6\") {
      #         echo "inno installed successfully"
      #       } else {
      #         throw "could not find inno's installation folder"
      #       }
      #     }

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      # - name: Configure PATH
      #   run: echo "export PATH=$PATH:/c/Users/$USER/.cargo/bin:/c/Program\ Files\ \(x86\)/Inno\ Setup\ 6" > ~/.bashrc

      - name: Configure GTK4
        run: |
          Add-Content $env:GITHUB_ENV "PKG_CONFIG_PATH=C:\gtk-build\gtk\x64\release\lib\pkgconfig;C:\Program Files\OpenSSL\lib\pkgconfig"
          Add-Content $env:GITHUB_ENV "PATH=C:\gtk-build\gtk\x64\release\bin;$env:PATH"
          Add-Content $env:GITHUB_ENV "LIB=C:\gtk-build\gtk\x64\release\lib;$env:LIB"
          Add-Content $env:GITHUB_ENV "INCLUDE=C:\gtk-build\gtk\x64\release\include;C:\gtk-build\gtk\x64\release\include\cairo;C:\gtk-build\gtk\x64\release\include\glib-2.0;C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0;C:\gtk-build\gtk\x64\release\lib\glib-2.0\include;$env:INCLUDE"

      # NOTE: I am using powershell here (in build steps. yes it is need for 
      # cargo install) so git linker does not load
      # instead of msvc link. That conflict will cause the build to fail
      # with crazy errors
      - name: Install Just and cargo-c
        run: cargo install just cargo-c

      - name: Install gvsbuild, meson & ninja
        run: |
          uv tool install gvsbuild
          uv tool install meson
          uv tool install ninja

      - name: Install GTK4
        if: steps.cache-gvsbuild-gtk.outputs.cache-hit != 'true'
        run: uv run gvsbuild build openssl gtk4 librsvg libadwaita adwaita-icon-theme --use-env

      - name: Verify Environment
        shell: bash
        run: |
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          echo "LIB=$LIB"
          echo "INCLUDE=$INCLUDE"
          echo "PATH=$PATH"
          pkg-config --modversion gtk4
          pkg-config --modversion libadwaita-1
          pkg-config --modversion openssl
          which link

      - name: "[DEBUG] just shell"
        run: just debug

      - name: Install Microsoft VisualStudio 2022 BuildTools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Remove Git link.exe
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\link.exe" -Force
          echo "PATH=$env:PATH" >> $env:GITHUB_ENV

      - name: Build app
        run: just install-exe

      # - name: Copy DLL
      #   run: |
      #     mkdir -p bundle/bin
      #     mkdir -p bundle/share/glib-2.0/schemas
      #     mkdir -p bundle/share/icons
      #     mkdir -p bundle/lib/gdk-pixbuf-2.0
      #
      #     GTK_DIR="C:/gtk-build/gtk/x64/release"
      #
      #     cp target/production/openworship.exe      bundle/bin/
      #     cp res/windows/openworship.ico            bundle/bin/
      #     cp -r "$GTK_DIR/share/glib-2.0/schemas/". bundle/share/glib-2.0/schemas/
      #     cp data/resources/com.openworship.app.gschema.xml bundle/share/glib-2.0/schemas/
      #     glib-compile-schemas bundle/share/glib-2.0/schemas/
      #     cp -r "$GTK_DIR/share/icons/."            bundle/share/icons/
      #     cp -r "$GTK_DIR/lib/gdk-pixbuf-2.0/."     bundle/lib/gdk-pixbuf-2.0/
      #
      #     GTK_BIN="C:/gtk-build/gtk/x64/release/bin"
      #     OUTPUT_DIR="bundle/bin"
      #
      #     mkdir -p "$OUTPUT_DIR"
      #
      #     # Only copy DLLs from the gtk-build path
      #     ldd target/production/openworship.exe \
      #       | grep -iv "windows" \
      #       | awk '{print $3}' \
      #       | while read -r dll; do
      #           filename=$(basename "$dll")
      #           echo "Copying: $filename"
      #           cp "$dll" "$OUTPUT_DIR/"
      #         done
      #
      #     echo "Creating installer output dir"
      #     mkdir build
      #
      #     echo "Done."

      - name: Set App version
        shell: bash
        run: echo "APP_VERSION=$(cargo pkgid | cut -d "@" -f2)" >> $GITHUB_ENV

      - name: Download VC++ Redist
        shell: bash
        run: |
          mkdir -p $APP_BUILDDIR/redist
          curl -L https://aka.ms/vs/17/release/vc_redist.x64.exe \
            -o $APP_BUILDDIR/redist/vc_redist.x64.exe

      - name: Get VC Redist version
        run: |
          $ver = (Get-Item ${{ env.APP_BUILDDIR }}\redist\vc_redist.x64.exe).VersionInfo.ProductVersion
          echo "VC_VERSION=v$ver" >> $env:GITHUB_ENV

      - name: "[DEBUG] Bundle structure"
        run: |
          tree /F /A "${{ env.APP_BUILDDIR }}\bundle"

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ${{ env.APP_BUILDDIR }}/inno.iss
          options: /O+ /DMyAppVersion=${{ env.APP_VERSION }} /DRedistVersion=${{ env.VC_VERSION }}

      - name: Upload installer to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: openworship-setup
          path: ${{ env.APP_BUILDDIR }}/build/openworship-setup.exe
          if-no-files-found: error

      # - name: Upload installer to assets
      #   uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     asset_paths: '["target/wix/*.exe"]'
      #   if: github.event_name == 'push' && github.ref_type == 'tag'
