# This action enables building release executables/installers and can be triggered manually or by release creation.
#
# Executables are built both for releases and for manually triggered runs, uploaded to artifacts and assets.
name: Release Mac Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  # push:
  # tags:
  #   - "*"
  # branches:
  #   - build/test
  # pull_request:
  # merge_group:

# Incremental compilation here isn't helpful
env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: macos-14
    env:
      BUILD_PREFIX: builddir/bundle

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install GTK4 (macOS)
        run: |
          brew install gtk4 librsvg libadwaita

      # On macOS, we need a proper Clang version, not Apple's custom version without wasm32 support
      - name: Install LLVM and Clang for macOS
        uses: KyleMayes/install-llvm-action@dec985c8d7b46a2f363ea1a78f660c946a3349ea # v2.0.1
        with:
          env: true
          version: 17

      # Because macOS, see https://andreasfertig.blog/2021/02/clang-and-gcc-on-macos-catalina-finding-the-include-paths/
      - name: Configure C compiler macOS
        run: |
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

      - name: Install glibtoolize (macOS)
        run: brew install libtool

      # Needed for hwloc
      - name: Install automake (macOS)
        run: brew install automake

      - name: Install meson
        run: brew install meson ninja

      - name: Install Just
        run: cargo install just
        
      - name: Configure cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build app
        run: just install-dmg

      - name: Upload dmg to artifacts (macOS)
        uses: actions/upload-artifact@v6
        with:
          name: openworship-macos-aarch64
          path: ${{ env.BUILD_PREFIX }}/*.dmg
          if-no-files-found: error

      # - name: Upload dmg to assets (macOS)
      #   uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     asset_paths: '["target/bundle/*.dmg"]'
      #   if: runner.os == 'macOS' && github.event_name == 'push' && github.ref_type == 'tag'
