# This action enables building release executables/installers and can be triggered manually or by release creation.
#
# Executables are built both for releases and for manually triggered runs, uploaded to artifacts and assets.
name: Release Mac Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  # push:
  # tags:
  #   - "*"
  # branches:
  #   - build/test
  # pull_request:
  # merge_group:

# Incremental compilation here isn't helpful
env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: macos-14
    env:
      BUILD_PREFIX: builddir/bundle

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install GTK4 
        run: brew install gtk4 librsvg libadwaita

      - name: Install app dependencies
        run: brew install libsamplerate

      - name: Install LLVM and build dependencies
        run: brew install cmake llvm

      - name: Configure LLVM and C compiler macOS
        run: |
          LLVM_PREFIX="$(brew --prefix llvm)"
          echo "PATH=$LLVM_PREFIX/bin:$PATH" >> $GITHUB_ENV
          echo "CC=$LLVM_PREFIX/bin/clang" >> $GITHUB_ENV
          echo "CXX=$LLVM_PREFIX/bin/clang++" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=$LLVM_PREFIX/lib" >> $GITHUB_ENV
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

          echo "PKG_CONFIG_PATH=$(brew --prefix libsamplerate)/lib/pkgconfig:$(brew --prefix)/lib/pkgconfig" >> "$GITHUB_ENV"

      - name: Install glibtoolize (macOS)
        run: brew install libtool

      # Needed for hwloc
      - name: Install automake (macOS)
        run: brew install automake

      - name: Install meson
        run: brew install meson ninja

      - name: Install Just
        run: cargo install just
        
      - name: Configure cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build app
        run: just install-dmg
        env:
          CMAKE_POLICY_VERSION_MINIMUM: "3.5" #because of libsamplerate

      - name: Upload dmg to artifacts (macOS)
        uses: actions/upload-artifact@v6
        with:
          name: openworship-macos-aarch64
          path: ${{ env.BUILD_PREFIX }}/*.dmg
          if-no-files-found: error

      # - name: Upload dmg to assets (macOS)
      #   uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     asset_paths: '["target/bundle/*.dmg"]'
      #   if: runner.os == 'macOS' && github.event_name == 'push' && github.ref_type == 'tag'
